/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.MenuBar;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;


/**
 *
 * @author qendrimrexhepi
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        //getContentPane().setBackground(Color.BLUE);
        setLocationRelativeTo(null); 
        //desktopPane desktop = new JDesktop(); desktop.setBackground( Color.RED ); 
    }
   
    public MainForm(int userRoli){
        initComponents();
        //Nese doni me bo max screen e shkruni kodin me poshte
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        getContentPane().setBackground(Color.ORANGE);
        setLocationRelativeTo(null);
        if(userRoli!=1){
            klientiButton.setVisible(false);
            pagesaButton.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ImageIcon icon=new ImageIcon(getClass().getResource("/FOTOGRAFIA/befiti.jpg"));
        Image img=icon.getImage();
        desktopPane = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g)
            {
                g.drawImage(img,0,0,getWidth(),
                    getHeight(),this);

            }
        };
        adminLabel = new javax.swing.JLabel();
        menagjeriButton = new javax.swing.JButton();
        paisjetButton = new javax.swing.JButton();
        zhveshtoreButton = new javax.swing.JButton();
        trajneriButton = new javax.swing.JButton();
        puntoriButton = new javax.swing.JButton();
        pagesaButton = new javax.swing.JButton();
        stafiButton = new javax.swing.JButton();
        fitnesiButton = new javax.swing.JButton();
        klientiButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        fitnesiMenu = new javax.swing.JMenu();
        fitnesiMenuItem = new javax.swing.JMenuItem();
        paisjetMenuItem = new javax.swing.JMenuItem();
        zhveshtoreMenuItem = new javax.swing.JMenuItem();
        stafiMenu = new javax.swing.JMenu();
        stafiMenuItem = new javax.swing.JMenuItem();
        menagjeriMenuItem = new javax.swing.JMenuItem();
        trajneriMenuItem = new javax.swing.JMenuItem();
        puntoriMenuItem = new javax.swing.JMenuItem();
        klientiMenu = new javax.swing.JMenu();
        klientiMenuItem = new javax.swing.JMenuItem();
        pagesaMenu = new javax.swing.JMenu();
        pagesaMenuItem = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        adminLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(255, 255, 255));
        adminLabel.setText("BEFIT");

        menagjeriButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        menagjeriButton.setText("Menagjeri");
        menagjeriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menagjeriButtonActionPerformed(evt);
            }
        });

        paisjetButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        paisjetButton.setText("Paisjet");
        paisjetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisjetButtonActionPerformed(evt);
            }
        });

        zhveshtoreButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        zhveshtoreButton.setText("Zhveshtore");
        zhveshtoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zhveshtoreButtonActionPerformed(evt);
            }
        });

        trajneriButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        trajneriButton.setText("Trajneri");
        trajneriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trajneriButtonActionPerformed(evt);
            }
        });

        puntoriButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        puntoriButton.setText("Puntori");
        puntoriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoriButtonActionPerformed(evt);
            }
        });

        pagesaButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        pagesaButton.setText("Pagesa");
        pagesaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesaButtonActionPerformed(evt);
            }
        });

        stafiButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        stafiButton.setText("Stafi");
        stafiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stafiButtonActionPerformed(evt);
            }
        });

        fitnesiButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        fitnesiButton.setText("Fitnesi");
        fitnesiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnesiButtonActionPerformed(evt);
            }
        });

        klientiButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        klientiButton.setText("Klienti");
        klientiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klientiButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(klientiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisjetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(fitnesiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(stafiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menagjeriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(trajneriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zhveshtoreButton)
                    .addComponent(pagesaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntoriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminLabel)
                .addGap(33, 33, 33)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menagjeriButton)
                    .addComponent(stafiButton)
                    .addComponent(fitnesiButton)
                    .addComponent(trajneriButton)
                    .addComponent(puntoriButton))
                .addGap(59, 59, 59)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(klientiButton)
                    .addComponent(pagesaButton))
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(zhveshtoreButton))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(paisjetButton)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        desktopPane.setLayer(adminLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(menagjeriButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(paisjetButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(zhveshtoreButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(trajneriButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(puntoriButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(pagesaButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(stafiButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(fitnesiButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(klientiButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        fileMenu.setText("File");
        MenuBar.add(fileMenu);

        editMenu.setText("Edit");
        MenuBar.add(editMenu);

        fitnesiMenu.setText("Fitnesi");

        fitnesiMenuItem.setText("Fitnesi");
        fitnesiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fitnesiMenuItemActionPerformed(evt);
            }
        });
        fitnesiMenu.add(fitnesiMenuItem);

        paisjetMenuItem.setText("Paisjet");
        paisjetMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisjetMenuItemActionPerformed(evt);
            }
        });
        fitnesiMenu.add(paisjetMenuItem);

        zhveshtoreMenuItem.setText("Zhveshtore");
        zhveshtoreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zhveshtoreMenuItemActionPerformed(evt);
            }
        });
        fitnesiMenu.add(zhveshtoreMenuItem);

        MenuBar.add(fitnesiMenu);

        stafiMenu.setText("Stafi");

        stafiMenuItem.setText("Stafi");
        stafiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stafiMenuItemActionPerformed(evt);
            }
        });
        stafiMenu.add(stafiMenuItem);

        menagjeriMenuItem.setText("Menagjeri");
        menagjeriMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menagjeriMenuItemActionPerformed(evt);
            }
        });
        stafiMenu.add(menagjeriMenuItem);

        trajneriMenuItem.setText("Trajneri");
        trajneriMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trajneriMenuItemActionPerformed(evt);
            }
        });
        stafiMenu.add(trajneriMenuItem);

        puntoriMenuItem.setText("Puntori");
        puntoriMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoriMenuItemActionPerformed(evt);
            }
        });
        stafiMenu.add(puntoriMenuItem);

        MenuBar.add(stafiMenu);

        klientiMenu.setText("Klienti");

        klientiMenuItem.setText("Klienti");
        klientiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klientiMenuItemActionPerformed(evt);
            }
        });
        klientiMenu.add(klientiMenuItem);

        MenuBar.add(klientiMenu);

        pagesaMenu.setText("Pagesa");

        pagesaMenuItem.setText("Pagesa");
        pagesaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesaMenuItemActionPerformed(evt);
            }
        });
        pagesaMenu.add(pagesaMenuItem);

        MenuBar.add(pagesaMenu);

        adminMenu.setText("Admin");
        MenuBar.add(adminMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void menagjeriMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menagjeriMenuItemActionPerformed
        // TODO add your handling code here:
        MenagjeriForm mf = new MenagjeriForm();
        desktopPane.add(mf);
        mf.show();
    }//GEN-LAST:event_menagjeriMenuItemActionPerformed

    private void fitnesiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnesiButtonActionPerformed
        // TODO add your handling code here:
        FitnesiForm ff = new FitnesiForm();
        desktopPane.add(ff);
        ff.show();
    }//GEN-LAST:event_fitnesiButtonActionPerformed

    private void fitnesiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fitnesiMenuItemActionPerformed
        // TODO add your handling code here:
        FitnesiForm ff = new FitnesiForm();
        desktopPane.add(ff);
        ff.show();
    }//GEN-LAST:event_fitnesiMenuItemActionPerformed

    private void stafiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stafiButtonActionPerformed
        // TODO add your handling code here:
        StafiForm sf = new StafiForm();
        desktopPane.add(sf);
        sf.show();
    }//GEN-LAST:event_stafiButtonActionPerformed

    private void stafiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stafiMenuItemActionPerformed
        // TODO add your handling code here:
        StafiForm sf = new StafiForm();
        desktopPane.add(sf);
        sf.show();
    }//GEN-LAST:event_stafiMenuItemActionPerformed

    private void menagjeriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menagjeriButtonActionPerformed
        // TODO add your handling code here:
        MenagjeriForm mf = new MenagjeriForm();
        desktopPane.add(mf);
        mf.show();
    }//GEN-LAST:event_menagjeriButtonActionPerformed

    private void trajneriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trajneriButtonActionPerformed
        // TODO add your handling code here:
        TrajneriForm tf = new TrajneriForm();
        desktopPane.add(tf);
        tf.show();
    }//GEN-LAST:event_trajneriButtonActionPerformed

    private void trajneriMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trajneriMenuItemActionPerformed
        // TODO add your handling code here:
        TrajneriForm tf = new TrajneriForm();
        desktopPane.add(tf);
        tf.show();
    }//GEN-LAST:event_trajneriMenuItemActionPerformed

    private void puntoriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoriButtonActionPerformed
        // TODO add your handling code here:
        PuntoriForm pf = new PuntoriForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_puntoriButtonActionPerformed

    private void puntoriMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoriMenuItemActionPerformed
        // TODO add your handling code here:
        PuntoriForm pf = new PuntoriForm();
        desktopPane.add(pf);
        pf.show();
    }//GEN-LAST:event_puntoriMenuItemActionPerformed

    private void klientiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klientiButtonActionPerformed
        // TODO add your handling code here:
        KlientiForm kf = new KlientiForm();
        desktopPane.add(kf);
        kf.show();
    }//GEN-LAST:event_klientiButtonActionPerformed

    private void klientiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klientiMenuItemActionPerformed
        // TODO add your handling code here:
        KlientiForm kf = new KlientiForm();
        desktopPane.add(kf);
        kf.show();
    }//GEN-LAST:event_klientiMenuItemActionPerformed

    private void pagesaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesaButtonActionPerformed
        // TODO add your handling code here:
        PagesaForm paf = new PagesaForm();
        desktopPane.add(paf);
        paf.show();
    }//GEN-LAST:event_pagesaButtonActionPerformed

    private void pagesaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesaMenuItemActionPerformed
        // TODO add your handling code here:
        PagesaForm paf = new PagesaForm();
        desktopPane.add(paf);
        paf.show();
    }//GEN-LAST:event_pagesaMenuItemActionPerformed

    private void paisjetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisjetButtonActionPerformed
        // TODO add your handling code here:
        PaisjetForm psf = new PaisjetForm();
        desktopPane.add(psf);
        psf.show();
    }//GEN-LAST:event_paisjetButtonActionPerformed

    private void paisjetMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisjetMenuItemActionPerformed
        // TODO add your handling code here:
        PaisjetForm psf = new PaisjetForm();
        desktopPane.add(psf);
        psf.show();
    }//GEN-LAST:event_paisjetMenuItemActionPerformed

    private void zhveshtoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zhveshtoreButtonActionPerformed
        // TODO add your handling code here:
        ZhveshtoreForm zhf = new ZhveshtoreForm();
        desktopPane.add(zhf);
        zhf.show();
    }//GEN-LAST:event_zhveshtoreButtonActionPerformed

    private void zhveshtoreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zhveshtoreMenuItemActionPerformed
        // TODO add your handling code here:
        ZhveshtoreForm zhf = new ZhveshtoreForm();
        desktopPane.add(zhf);
        zhf.show();
    }//GEN-LAST:event_zhveshtoreMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);  
                
            }           
        });
    }
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton fitnesiButton;
    private javax.swing.JMenu fitnesiMenu;
    private javax.swing.JMenuItem fitnesiMenuItem;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton klientiButton;
    private javax.swing.JMenu klientiMenu;
    private javax.swing.JMenuItem klientiMenuItem;
    private javax.swing.JButton menagjeriButton;
    private javax.swing.JMenuItem menagjeriMenuItem;
    private javax.swing.JButton pagesaButton;
    private javax.swing.JMenu pagesaMenu;
    private javax.swing.JMenuItem pagesaMenuItem;
    private javax.swing.JButton paisjetButton;
    private javax.swing.JMenuItem paisjetMenuItem;
    private javax.swing.JButton puntoriButton;
    private javax.swing.JMenuItem puntoriMenuItem;
    private javax.swing.JButton stafiButton;
    private javax.swing.JMenu stafiMenu;
    private javax.swing.JMenuItem stafiMenuItem;
    private javax.swing.JButton trajneriButton;
    private javax.swing.JMenuItem trajneriMenuItem;
    private javax.swing.JButton zhveshtoreButton;
    private javax.swing.JMenuItem zhveshtoreMenuItem;
    // End of variables declaration//GEN-END:variables
}
