/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Menagjeri;
import BLL.Stafi;
import DAL.FitnesiException;
import DAL.MenagjeriRepository;
import DAL.StafiRepository;
import GUI.Model.MenagjeriTableModel;
import GUI.Model.StafiComboBoxModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author qendrimrexhepi
 */
public class MenagjeriForm extends javax.swing.JInternalFrame {

    
    MenagjeriRepository mr = new MenagjeriRepository();
    StafiRepository ssr = new StafiRepository();
    MenagjeriTableModel mtm = new MenagjeriTableModel();
    StafiComboBoxModel scmb = new StafiComboBoxModel();
    /**
     * Creates new form MenagjeriForm
     */
    public MenagjeriForm() {
        initComponents();
        loadTable();
        tabelaSelectedIndexChange();
        loadComboBox();
    }
    
    public void loadTable(){
        try{
            List<Menagjeri> lista = mr.findALL();
            mtm.addList(lista);
            table.setModel(mtm);
            mtm.fireTableDataChanged();
        }catch(FitnesiException ex){
            Logger.getLogger(FitnesiForm.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    private void tabelaSelectedIndexChange(){
        final ListSelectionModel rowSM = table.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(e.getValueIsAdjusting()){
                    return;
                }
                
                ListSelectionModel rowSM = (ListSelectionModel) e.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if(selectedIndex > -1){
                    Menagjeri m = mtm.getMenagjeri(selectedIndex);
                    midTextField.setText(m.getMid().toString());
                    scmb.setSelectedItem(m.getSid());
                    sidComboBox.repaint();
                    emriTextField.setText(m.getEmri());
                    mbiemriTextField.setText(m.getMbiemri());
                    moshaTextField.setText(m.getMosha().toString());
                    nrpersonalTextField.setText(m.getNrPersonal().toString());
                    nrtelefonitTextField.setText(m.getNrTelefonit().toString());
                    gjiniaTextField.setText(m.getGjinia().toString()); 
                    qytetiTextField.setText(m.getQyteti());
                    adresaTextField.setText(m.getAdresa());
                }
            }
        });
    }
    
    public void loadComboBox(){
        try{
            List<Stafi> lista = ssr.findALL();
            scmb.add(lista);
            sidComboBox.setModel(scmb);
            sidComboBox.repaint();
        }catch(FitnesiException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menagjeriLabel = new javax.swing.JLabel();
        midLabel = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        emriLabel = new javax.swing.JLabel();
        mbiemriLabel = new javax.swing.JLabel();
        moshaLabel = new javax.swing.JLabel();
        nrpersonalLabel = new javax.swing.JLabel();
        nrtelefonitLabel = new javax.swing.JLabel();
        gjiniaLabel = new javax.swing.JLabel();
        qytetiLabel = new javax.swing.JLabel();
        adresaLabel = new javax.swing.JLabel();
        midTextField = new javax.swing.JTextField();
        emriTextField = new javax.swing.JTextField();
        mbiemriTextField = new javax.swing.JTextField();
        moshaTextField = new javax.swing.JTextField();
        nrpersonalTextField = new javax.swing.JTextField();
        nrtelefonitTextField = new javax.swing.JTextField();
        gjiniaTextField = new javax.swing.JTextField();
        qytetiTextField = new javax.swing.JTextField();
        adresaTextField = new javax.swing.JTextField();
        sidComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));

        menagjeriLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        menagjeriLabel.setForeground(new java.awt.Color(255, 255, 255));
        menagjeriLabel.setText("MENAGJERI");

        midLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        midLabel.setForeground(new java.awt.Color(255, 255, 255));
        midLabel.setText("MID:");

        sidLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sidLabel.setForeground(new java.awt.Color(255, 255, 255));
        sidLabel.setText("SID:");

        emriLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        emriLabel.setForeground(new java.awt.Color(255, 255, 255));
        emriLabel.setText("Emri:");

        mbiemriLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mbiemriLabel.setForeground(new java.awt.Color(255, 255, 255));
        mbiemriLabel.setText("Mbiemri:");

        moshaLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        moshaLabel.setForeground(new java.awt.Color(255, 255, 255));
        moshaLabel.setText("Mosha:");

        nrpersonalLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        nrpersonalLabel.setForeground(new java.awt.Color(255, 255, 255));
        nrpersonalLabel.setText("NrPersonal:");

        nrtelefonitLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        nrtelefonitLabel.setForeground(new java.awt.Color(255, 255, 255));
        nrtelefonitLabel.setText("NrTelefonit:");

        gjiniaLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        gjiniaLabel.setForeground(new java.awt.Color(255, 255, 255));
        gjiniaLabel.setText("Gjinia:");

        qytetiLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        qytetiLabel.setForeground(new java.awt.Color(255, 255, 255));
        qytetiLabel.setText("Qyteti:");

        adresaLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        adresaLabel.setForeground(new java.awt.Color(255, 255, 255));
        adresaLabel.setText("Adresa:");

        midTextField.setEnabled(false);

        sidComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(moshaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(midLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(qytetiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(qytetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(midTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(moshaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(adresaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sidLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nrpersonalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nrpersonalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(adresaTextField)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(sidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nrtelefonitLabel)
                                    .addComponent(emriLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(menagjeriLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(nrtelefonitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gjiniaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(emriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(mbiemriLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gjiniaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(menagjeriLabel)
                .addGap(57, 57, 57)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(midLabel)
                    .addComponent(sidLabel)
                    .addComponent(emriLabel)
                    .addComponent(mbiemriLabel)
                    .addComponent(midTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrpersonalLabel)
                    .addComponent(nrtelefonitLabel)
                    .addComponent(gjiniaLabel)
                    .addComponent(moshaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrpersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrtelefonitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gjiniaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moshaLabel))
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qytetiLabel)
                    .addComponent(adresaLabel)
                    .addComponent(qytetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        saveButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        saveButton.setText("Ruaj");
        saveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cancelButton.setText("Anulo");
        cancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deleteButton.setText("Fshije");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(cancelButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row != -1){
            Object[] ob = {"Po","Jo"};
            int i = JOptionPane.showOptionDialog(this,"A deshironi ta fshini?","Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if(i == 0){
                Menagjeri m = mtm.getMenagjeri(row);
                try{
                    mr.delete(m);
                }catch(FitnesiException ex){
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                }
                clear();
                loadTable();
            }else{
                clear();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgje per te fshire!");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            int row = table.getSelectedRow();
            if(row == -1){
                Menagjeri m = new Menagjeri();
                //p.setId(Integer.parseInt(idField.getText()));
                m.setSid((Stafi)scmb.getSelectedItem());
                m.setEmri(emriTextField.getText());
                m.setMbiemri(mbiemriTextField.getText());
                m.setMosha(Integer.parseInt(moshaTextField.getText()));
                m.setNrPersonal(Integer.parseInt(nrpersonalTextField.getText()));
                m.setNrTelefonit(Integer.parseInt(nrtelefonitTextField.getText()));
                m.setGjinia(gjiniaTextField.getText().charAt(0));
                m.setQyteti(qytetiTextField.getText());
                m.setAdresa(adresaTextField.getText());
                mr.create(m);
            }else{
                Menagjeri m = mtm.getMenagjeri(row);
                //Id nuk e lejojm me ndryshu vetem emertimin ose fielda tjere qe mundeni me pas
                m.setSid((Stafi)scmb.getSelectedItem());
                m.setEmri(emriTextField.getText());
                m.setMbiemri(mbiemriTextField.getText());
                m.setMosha(Integer.parseInt(moshaTextField.getText()));
                m.setNrPersonal(Integer.parseInt(nrpersonalTextField.getText()));
                m.setNrTelefonit(Integer.parseInt(nrtelefonitTextField.getText()));
                m.setGjinia(gjiniaTextField.getText().charAt(0));
                m.setQyteti(qytetiTextField.getText());
                m.setAdresa(adresaTextField.getText());
                mr.edit(m);
            }
            //E krijojm ni metode per me i clear fieldat mbasi ti shtojme
            clear();
            loadTable();
        }catch(FitnesiException ex){
            JOptionPane.showMessageDialog(this, "E dhena ekziston!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void clear(){
        table.clearSelection();
        midTextField.setText("");
        emriTextField.setText("");
        mbiemriTextField.setText("");
        moshaTextField.setText("");
        nrpersonalTextField.setText("");
        nrtelefonitTextField.setText("");
        gjiniaTextField.setText("");
        qytetiTextField.setText("");
        adresaTextField.setText("");
        //pcmb.setSelectedItem(null);
        sidComboBox.setSelectedIndex(-1);
        sidComboBox.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresaLabel;
    private javax.swing.JTextField adresaTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emriLabel;
    private javax.swing.JTextField emriTextField;
    private javax.swing.JLabel gjiniaLabel;
    private javax.swing.JTextField gjiniaTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mbiemriLabel;
    private javax.swing.JTextField mbiemriTextField;
    private javax.swing.JLabel menagjeriLabel;
    private javax.swing.JLabel midLabel;
    private javax.swing.JTextField midTextField;
    private javax.swing.JLabel moshaLabel;
    private javax.swing.JTextField moshaTextField;
    private javax.swing.JLabel nrpersonalLabel;
    private javax.swing.JTextField nrpersonalTextField;
    private javax.swing.JLabel nrtelefonitLabel;
    private javax.swing.JTextField nrtelefonitTextField;
    private javax.swing.JLabel qytetiLabel;
    private javax.swing.JTextField qytetiTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox sidComboBox;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
