/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.View;

import BLL.Puntori;
import BLL.Stafi;
import DAL.FitnesiException;
import DAL.PuntoriRepository;
import DAL.StafiRepository;
import GUI.Model.PuntoriTableModel;
import GUI.Model.StafiComboBoxModel;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author qendrimrexhepi
 */
public class PuntoriForm extends javax.swing.JInternalFrame {

    PuntoriRepository pr = new PuntoriRepository();
    StafiRepository ssr = new StafiRepository();
    PuntoriTableModel ptm = new PuntoriTableModel();
    StafiComboBoxModel scmb = new StafiComboBoxModel();
    /**
     * Creates new form PuntoriForm
     */
    public PuntoriForm() {
        initComponents();
        loadTable();
        tabelaSelectedIndexChange();
        loadComboBox();
    }
    
    public void loadTable(){
        try{
            List<Puntori> lista = pr.findALL();
            ptm.addList(lista);
            table.setModel(ptm);
            ptm.fireTableDataChanged();
        }catch(FitnesiException ex){
            Logger.getLogger(FitnesiForm.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    
    private void tabelaSelectedIndexChange(){
        final ListSelectionModel rowSM = table.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener(){

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(e.getValueIsAdjusting()){
                    return;
                }
                
                ListSelectionModel rowSM = (ListSelectionModel) e.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if(selectedIndex > -1){
                    Puntori p = ptm.getPuntori(selectedIndex);
                    pidTextField.setText(p.getPid().toString());
                    scmb.setSelectedItem(p.getSid());
                    sidComboBox.repaint();
                    emriTextField.setText(p.getEmri());
                    mbiemriTextField.setText(p.getMbiemri());
                    moshaTextField.setText(p.getMosha().toString());
                    gjiniaTextField.setText(p.getGjinia().toString());
                    nrtelefonitTextField.setText(p.getNrTelefonit().toString()); 
                    qytetiTextField.setText(p.getQyteti());
                    adresaTextField.setText(p.getAdresa());
                }
            }
        });
    }
    
    public void loadComboBox(){
        try{
            List<Stafi> lista = ssr.findALL();
            scmb.add(lista);
            sidComboBox.setModel(scmb);
            sidComboBox.repaint();
        }catch(FitnesiException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        puntoriLabel = new javax.swing.JLabel();
        pidLabel = new javax.swing.JLabel();
        sidLabel = new javax.swing.JLabel();
        emriLabel = new javax.swing.JLabel();
        mbiemriLabel = new javax.swing.JLabel();
        gjiniaLabel = new javax.swing.JLabel();
        moshaLabel = new javax.swing.JLabel();
        nrtelefonitLabel = new javax.swing.JLabel();
        qytetiLabel = new javax.swing.JLabel();
        adresaLabel = new javax.swing.JLabel();
        pidTextField = new javax.swing.JTextField();
        sidComboBox = new javax.swing.JComboBox();
        emriTextField = new javax.swing.JTextField();
        mbiemriTextField = new javax.swing.JTextField();
        moshaTextField = new javax.swing.JTextField();
        gjiniaTextField = new javax.swing.JTextField();
        nrtelefonitTextField = new javax.swing.JTextField();
        qytetiTextField = new javax.swing.JTextField();
        adresaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        filechooserTextField = new javax.swing.JTextField();
        filechooserButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));

        puntoriLabel.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        puntoriLabel.setForeground(new java.awt.Color(255, 255, 255));
        puntoriLabel.setText("PUNTORI");

        pidLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pidLabel.setForeground(new java.awt.Color(255, 255, 255));
        pidLabel.setText("PID:");

        sidLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sidLabel.setForeground(new java.awt.Color(255, 255, 255));
        sidLabel.setText("SID:");

        emriLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        emriLabel.setForeground(new java.awt.Color(255, 255, 255));
        emriLabel.setText("Emri:");

        mbiemriLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        mbiemriLabel.setForeground(new java.awt.Color(255, 255, 255));
        mbiemriLabel.setText("Mbiemri:");

        gjiniaLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        gjiniaLabel.setForeground(new java.awt.Color(255, 255, 255));
        gjiniaLabel.setText("Gjinia:");

        moshaLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        moshaLabel.setForeground(new java.awt.Color(255, 255, 255));
        moshaLabel.setText("Mosha:");

        nrtelefonitLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        nrtelefonitLabel.setForeground(new java.awt.Color(255, 255, 255));
        nrtelefonitLabel.setText("NrTelefonit:");

        qytetiLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        qytetiLabel.setForeground(new java.awt.Color(255, 255, 255));
        qytetiLabel.setText("Qyteti:");

        adresaLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        adresaLabel.setForeground(new java.awt.Color(255, 255, 255));
        adresaLabel.setText("Adresa:");

        pidTextField.setEnabled(false);

        sidComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        filechooserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechooserTextFieldActionPerformed(evt);
            }
        });

        filechooserButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        filechooserButton.setText("FileChooser");
        filechooserButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        filechooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechooserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(moshaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                    .addComponent(adresaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moshaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gjiniaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(filechooserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sidComboBox, 0, 69, Short.MAX_VALUE)
                    .addComponent(gjiniaTextField)
                    .addComponent(filechooserTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emriLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrtelefonitLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nrtelefonitTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(emriTextField))
                .addGap(46, 46, 46)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mbiemriLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qytetiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qytetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(puntoriLabel)
                        .addGap(391, 391, 391))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(puntoriLabel)
                .addGap(50, 50, 50)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pidLabel)
                    .addComponent(sidLabel)
                    .addComponent(emriLabel)
                    .addComponent(mbiemriLabel)
                    .addComponent(pidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sidComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbiemriTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moshaLabel)
                    .addComponent(nrtelefonitLabel)
                    .addComponent(qytetiLabel)
                    .addComponent(gjiniaLabel)
                    .addComponent(gjiniaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nrtelefonitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qytetiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moshaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adresaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresaLabel)
                    .addComponent(filechooserButton)
                    .addComponent(filechooserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        saveButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        saveButton.setText("Ruaj");
        saveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deleteButton.setText("Fshije");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cancelButton.setText("Anulo");
        cancelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            int row = table.getSelectedRow();
            if(row == -1){
                Puntori p = new Puntori();
                //t.setTid(Integer.parseInt(TidTextField.getText()));
                p.setSid((Stafi)scmb.getSelectedItem());
                p.setEmri(emriTextField.getText());
                p.setMbiemri(mbiemriTextField.getText());
                p.setMosha(Integer.parseInt(moshaTextField.getText()));
                p.setGjinia(gjiniaTextField.getText().charAt(0));  
                p.setNrTelefonit(Integer.parseInt(nrtelefonitTextField.getText())); 
                p.setQyteti(qytetiTextField.getText());
                p.setAdresa(adresaTextField.getText());
                pr.create(p);
            }else{
                Puntori p = ptm.getPuntori(row);
                //Id nuk e lejojm me ndryshu vetem emertimin ose fielda tjere qe mundeni me pas
                p.setSid((Stafi)scmb.getSelectedItem());
                p.setEmri(emriTextField.getText());
                p.setMbiemri(mbiemriTextField.getText());
                p.setMosha(Integer.parseInt(moshaTextField.getText()));
                p.setGjinia(gjiniaTextField.getText().charAt(0));  
                p.setNrTelefonit(Integer.parseInt(nrtelefonitTextField.getText())); 
                p.setQyteti(qytetiTextField.getText());
                p.setAdresa(adresaTextField.getText());
                pr.edit(p);
            }
            //E krijojm ni metode per me i clear fieldat mbasi ti shtojme
            clear();
            loadTable();
        }catch(FitnesiException ex){
            JOptionPane.showMessageDialog(this, "E dhena ekziston!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int row = table.getSelectedRow();
        if(row != -1){
            Object[] ob = {"Po","Jo"};
            int i = JOptionPane.showOptionDialog(this,"A deshironi ta fshini?","Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if(i == 0){
                Puntori p = ptm.getPuntori(row);
                try{
                    pr.delete(p);
                }catch(FitnesiException ex){
                    JOptionPane.showMessageDialog(this,ex.getMessage());
                }
                clear();
                loadTable();
            }else{
                clear();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgje per te fshire!");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void filechooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechooserButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        filechooserTextField.setText(filename);
    }//GEN-LAST:event_filechooserButtonActionPerformed

    private void filechooserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechooserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filechooserTextFieldActionPerformed

    public void clear(){
        table.clearSelection();
        pidTextField.setText("");
        emriTextField.setText("");
        mbiemriTextField.setText("");
        moshaTextField.setText("");
        gjiniaTextField.setText("");
        nrtelefonitTextField.setText("");
        qytetiTextField.setText("");
        adresaTextField.setText("");
        //pcmb.setSelectedItem(null);
        sidComboBox.setSelectedIndex(-1);
        sidComboBox.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresaLabel;
    private javax.swing.JTextField adresaTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emriLabel;
    private javax.swing.JTextField emriTextField;
    private javax.swing.JButton filechooserButton;
    private javax.swing.JTextField filechooserTextField;
    private javax.swing.JLabel gjiniaLabel;
    private javax.swing.JTextField gjiniaTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mbiemriLabel;
    private javax.swing.JTextField mbiemriTextField;
    private javax.swing.JLabel moshaLabel;
    private javax.swing.JTextField moshaTextField;
    private javax.swing.JLabel nrtelefonitLabel;
    private javax.swing.JTextField nrtelefonitTextField;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JTextField pidTextField;
    private javax.swing.JLabel puntoriLabel;
    private javax.swing.JLabel qytetiLabel;
    private javax.swing.JTextField qytetiTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox sidComboBox;
    private javax.swing.JLabel sidLabel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
